import type { LocalHealthReport } from './score.js';

const gradeLabels: Record<string, string> = {
  healthy: 'HEALTHY',
  attention: 'ATTENTION',
  critical: 'CRITICAL',
};

const signalLabel = (policyKey: string): string => policyKey.replaceAll('_', ' ');

export const renderTerminalReport = (report: LocalHealthReport): string => {
  const { computation } = report;
  const lines: string[] = [];
  const repository = report.repositorySlug
    ? `${report.repositorySlug.owner}/${report.repositorySlug.name}`
    : 'local repository';

  lines.push(`ForgeOps automation health — ${repository}`);
  lines.push('');
  lines.push(
    `Score: ${computation.score}/100 (${gradeLabels[computation.grade] ?? computation.grade})`,
  );
  lines.push('');

  for (const signal of computation.signals) {
    const marker = signal.status === 'compliant' ? '[x]' : '[ ]';
    lines.push(
      `${marker} ${signalLabel(signal.policyKey)} (${signal.earnedPoints}/${signal.weight}) — ${signal.details}`,
    );
  }

  lines.push('');

  if (report.ciDataSource === 'github') {
    lines.push(
      `CI reliability: ${computation.ciReliability.earnedPoints}/${computation.ciReliability.weight} (${computation.ciReliability.successfulRunCount} of ${computation.ciReliability.consideredRunCount} recent runs succeeded)`,
    );
  } else {
    lines.push(`CI reliability: 0/${computation.ciReliability.weight} — ${report.ciDataNote ?? 'unavailable'}`);
  }

  if (computation.blockersPenalty.penaltyPoints > 0) {
    lines.push(
      `Blockers penalty: -${computation.blockersPenalty.penaltyPoints} (${computation.blockersPenalty.openBlockersCount} open blocker(s))`,
    );
  }

  return lines.join('\n');
};

export const HEALTH_COMMENT_MARKER = '<!-- forgeops-health -->';

export const renderMarkdownReport = (report: LocalHealthReport): string => {
  const { computation } = report;
  const repository = report.repositorySlug
    ? `${report.repositorySlug.owner}/${report.repositorySlug.name}`
    : 'local repository';
  const gradeEmoji =
    computation.grade === 'healthy' ? '🟢' : computation.grade === 'attention' ? '🟡' : '🔴';
  const lines: string[] = [];

  lines.push(HEALTH_COMMENT_MARKER);
  lines.push(`## ForgeOps automation health — ${repository}`);
  lines.push('');
  lines.push(`${gradeEmoji} **${computation.score}/100** (\`${computation.grade}\`)`);
  lines.push('');
  lines.push('| Signal | Status | Points |');
  lines.push('| --- | --- | --- |');

  for (const signal of computation.signals) {
    const status = signal.status === 'compliant' ? '✅ compliant' : '❌ non compliant';
    lines.push(
      `| ${signalLabel(signal.policyKey)} | ${status} | ${signal.earnedPoints}/${signal.weight} |`,
    );
  }

  lines.push('');

  if (report.ciDataSource === 'github') {
    lines.push(
      `CI reliability: **${computation.ciReliability.earnedPoints}/${computation.ciReliability.weight}** — ${computation.ciReliability.successfulRunCount} of ${computation.ciReliability.consideredRunCount} recent runs succeeded.`,
    );
  } else {
    lines.push(`CI reliability: **0/${computation.ciReliability.weight}** — ${report.ciDataNote ?? 'unavailable'}`);
  }

  if (computation.blockersPenalty.penaltyPoints > 0) {
    lines.push(
      `Blockers penalty: **-${computation.blockersPenalty.penaltyPoints}** (${computation.blockersPenalty.openBlockersCount} open blocker(s)).`,
    );
  }

  lines.push('');
  lines.push('_Generated by [ForgeOps](https://github.com/alessandrolsdev/forge-ops)._');

  return lines.join('\n');
};
