name: Typecheck

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: typecheck-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: typecheck
    uses: ./.github/workflows/reusable-node-checks.yml
    with:
      task: typecheck
      generate-prisma-client: true
      timeout-minutes: 12
